GLOBAL_LIST_INIT(character_accents, list("No accent",
//	"Dwarven accent",
//	"Dwarf Gibberish accent",
	"Otavan accent",
	"North Elven accent",
	"Zybantine (Traditional) accent",
//	"East Elven accent",
	"Grenzelhoftian accent",
//	"Otavian accent",
	"Hammerholdian accent",
	"Old Imperial accent",
//	"Aasimari accent",
//	"Lupian accent",
//	/Sissean accent",
	"Etruscan accent",
//	"Half Orc accent",
//	"Urban Orc accent",
//	"Drakian accent",
//	"Inzectoid accent",
//	"Feline accent",
	"Abyssal accent"
//	"Slopes accent",
//	"Gronn accent",
//	"Axian accent"
))
