// Soft cleanup for THRALLS_* defines introduced by vampires_defines.dm.

#ifdef THRALLS_METHUSELAH
#undef THRALLS_METHUSELAH
#endif

#ifdef THRALLS_ANCILLAE
#undef THRALLS_ANCILLAE
#endif

#ifdef THRALLS_NEONATE
#undef THRALLS_NEONATE
#endif

#ifdef THRALLS_THINBLOOD
#undef THRALLS_THINBLOOD
#endif

#ifdef THRALLS_DEFAULT
#undef THRALLS_DEFAULT
#endif

#ifdef TA_VAMP_CONVERT_ANCILLAE_RESEARCH_COST
#undef TA_VAMP_CONVERT_ANCILLAE_RESEARCH_COST
#endif

#ifdef TA_VAMP_CONVERT_NEONATE_RESEARCH_COST
#undef TA_VAMP_CONVERT_NEONATE_RESEARCH_COST
#endif

#ifdef TA_VAMP_CONVERT_ANCILLAE_MAXBLOODPOOL_COST
#undef TA_VAMP_CONVERT_ANCILLAE_MAXBLOODPOOL_COST
#endif

#ifdef TA_VAMP_CONVERT_NEONATE_MAXBLOODPOOL_COST
#undef TA_VAMP_CONVERT_NEONATE_MAXBLOODPOOL_COST
#endif

#ifdef TA_VAMP_CONVERT_OFFER_RESEARCH_REWARD
#undef TA_VAMP_CONVERT_OFFER_RESEARCH_REWARD
#endif

#ifdef TA_VAMP_CONVERT_OFFER_MAXBLOODPOOL_REWARD
#undef TA_VAMP_CONVERT_OFFER_MAXBLOODPOOL_REWARD
#endif

#ifdef TA_VAMP_DRAIN_RESEARCH_REWARD
#undef TA_VAMP_DRAIN_RESEARCH_REWARD
#endif

#ifdef TA_VAMP_DRAIN_MAXBLOODPOOL_REWARD
#undef TA_VAMP_DRAIN_MAXBLOODPOOL_REWARD
#endif

#ifdef TA_VAMP_REWARD_NEONATE_MAXBLOODPOOL_CAP
#undef TA_VAMP_REWARD_NEONATE_MAXBLOODPOOL_CAP
#endif

#ifdef TA_VAMP_REWARD_ANCILLAE_MAXBLOODPOOL_CAP
#undef TA_VAMP_REWARD_ANCILLAE_MAXBLOODPOOL_CAP
#endif

#ifdef TA_VAMP_CONVERT_HIGHPOP_THRESHOLD
#undef TA_VAMP_CONVERT_HIGHPOP_THRESHOLD
#endif

#ifdef TA_VAMP_CONVERT_PALLID_THRESHOLD
#undef TA_VAMP_CONVERT_PALLID_THRESHOLD
#endif

#ifdef TA_VAMP_CONVERT_RESIST_STUN_TIME
#undef TA_VAMP_CONVERT_RESIST_STUN_TIME
#endif

#ifdef TA_VAMP_DRAIN_MIN_BLOOD_VOLUME
#undef TA_VAMP_DRAIN_MIN_BLOOD_VOLUME
#endif

#ifdef TA_VAMP_DRAIN_STUN_TIME
#undef TA_VAMP_DRAIN_STUN_TIME
#endif

#ifdef TA_TRAIT_PALLID_DRAIN_IMMUNE
#undef TA_TRAIT_PALLID_DRAIN_IMMUNE
#endif

#ifdef TA_TRAIT_PALLID_DRAINED_ONCE
#undef TA_TRAIT_PALLID_DRAINED_ONCE
#endif

#ifdef TA_VAMP_LETHAL_BLOODDRINK_DELAY
#undef TA_VAMP_LETHAL_BLOODDRINK_DELAY
#endif

#ifdef TA_VAMP_LORD_FORCE_CONVERT
#undef TA_VAMP_LORD_FORCE_CONVERT
#endif

#ifdef TA_VAMP_DIABLERIE_DELAY
#undef TA_VAMP_DIABLERIE_DELAY
#endif

#ifdef TA_VAMP_DIABLERIE_RESEARCH_BONUS
#undef TA_VAMP_DIABLERIE_RESEARCH_BONUS
#endif

#ifdef MASQUERADE_COOLDOWN
#undef MASQUERADE_COOLDOWN
#endif

#ifdef TA_TRANSFIX_MIN_MSG_LENGTH
#undef TA_TRANSFIX_MIN_MSG_LENGTH
#endif

#ifdef TA_TRANSFIX_CHARS_PER_MINUTE
#undef TA_TRANSFIX_CHARS_PER_MINUTE
#endif

#ifdef TA_TRANSFIX_PASTE_STUN_TIME
#undef TA_TRANSFIX_PASTE_STUN_TIME
#endif

#ifdef TA_TRANSFIX_PASTE_INT_LOSS
#undef TA_TRANSFIX_PASTE_INT_LOSS
#endif

#ifdef TA_TRANSFIX_PASTE_DEATH_INT
#undef TA_TRANSFIX_PASTE_DEATH_INT
#endif
