#define RESIDENT_MANUSCRIPT_STATUS_COMMONER "commoner"
#define RESIDENT_MANUSCRIPT_STATUS_NOBLE "noble"

#define RESIDENT_MANUSCRIPT_VERIFICATION_NONE "none"
#define RESIDENT_MANUSCRIPT_VERIFICATION_UNKNOWN "unknown"
#define RESIDENT_MANUSCRIPT_VERIFICATION_REAL "real"
#define RESIDENT_MANUSCRIPT_VERIFICATION_FAKE "fake"

#define RESIDENT_MANUSCRIPT_SPECIAL_ITEM_NAME "Грамота жителя"

#define RESIDENT_MANUSCRIPT_FAKE_DEFECT_CHANCE 65
#define RESIDENT_MANUSCRIPT_MIN_DEFECTS 3
#define RESIDENT_MANUSCRIPT_MAX_DEFECTS 5

#define RESIDENT_SEAL_PRIORITY_FACTION_LOW   10
#define RESIDENT_SEAL_PRIORITY_ELDER         20
#define RESIDENT_SEAL_PRIORITY_FACTION_MID   25
#define RESIDENT_SEAL_PRIORITY_CHANCELLOR    40
#define RESIDENT_SEAL_PRIORITY_FACTION_HIGH  50
#define RESIDENT_SEAL_PRIORITY_HAND          60
#define RESIDENT_SEAL_PRIORITY_RULER         80
#define RESIDENT_SEAL_PRIORITY_KAISER        100
